// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: pkg/rpc/pb/bif_examine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadBifKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectName string `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Contents    []byte `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *UploadBifKeyRequest) Reset() {
	*x = UploadBifKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpc_pb_bif_examine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadBifKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBifKeyRequest) ProtoMessage() {}

func (x *UploadBifKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_pb_bif_examine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBifKeyRequest.ProtoReflect.Descriptor instead.
func (*UploadBifKeyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_pb_bif_examine_proto_rawDescGZIP(), []int{0}
}

func (x *UploadBifKeyRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *UploadBifKeyRequest) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type UploadBifKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *UploadBifKeyResponse) Reset() {
	*x = UploadBifKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpc_pb_bif_examine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadBifKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBifKeyResponse) ProtoMessage() {}

func (x *UploadBifKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_pb_bif_examine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBifKeyResponse.ProtoReflect.Descriptor instead.
func (*UploadBifKeyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_pb_bif_examine_proto_rawDescGZIP(), []int{1}
}

func (x *UploadBifKeyResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_pkg_rpc_pb_bif_examine_proto protoreflect.FileDescriptor

var file_pkg_rpc_pb_bif_examine_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x69, 0x66,
	0x5f, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x54, 0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x69, 0x66, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x42, 0x69, 0x66, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x32, 0x4f, 0x0a, 0x0a, 0x42, 0x69, 0x66, 0x45, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x12, 0x41,
	0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x69, 0x66, 0x4b, 0x65, 0x79, 0x12, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x69, 0x66, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x42, 0x69, 0x66, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_rpc_pb_bif_examine_proto_rawDescOnce sync.Once
	file_pkg_rpc_pb_bif_examine_proto_rawDescData = file_pkg_rpc_pb_bif_examine_proto_rawDesc
)

func file_pkg_rpc_pb_bif_examine_proto_rawDescGZIP() []byte {
	file_pkg_rpc_pb_bif_examine_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_pb_bif_examine_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_rpc_pb_bif_examine_proto_rawDescData)
	})
	return file_pkg_rpc_pb_bif_examine_proto_rawDescData
}

var file_pkg_rpc_pb_bif_examine_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_rpc_pb_bif_examine_proto_goTypes = []interface{}{
	(*UploadBifKeyRequest)(nil),  // 0: pb.UploadBifKeyRequest
	(*UploadBifKeyResponse)(nil), // 1: pb.UploadBifKeyResponse
}
var file_pkg_rpc_pb_bif_examine_proto_depIdxs = []int32{
	0, // 0: pb.BifExamine.UploadBifKey:input_type -> pb.UploadBifKeyRequest
	1, // 1: pb.BifExamine.UploadBifKey:output_type -> pb.UploadBifKeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_rpc_pb_bif_examine_proto_init() }
func file_pkg_rpc_pb_bif_examine_proto_init() {
	if File_pkg_rpc_pb_bif_examine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_rpc_pb_bif_examine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadBifKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_rpc_pb_bif_examine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadBifKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_rpc_pb_bif_examine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_pb_bif_examine_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_pb_bif_examine_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_pb_bif_examine_proto_msgTypes,
	}.Build()
	File_pkg_rpc_pb_bif_examine_proto = out.File
	file_pkg_rpc_pb_bif_examine_proto_rawDesc = nil
	file_pkg_rpc_pb_bif_examine_proto_goTypes = nil
	file_pkg_rpc_pb_bif_examine_proto_depIdxs = nil
}
