// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: pkg/rpc/pb/bif_examine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BifExamine_UploadBifKey_FullMethodName = "/pb.BifExamine/UploadBifKey"
)

// BifExamineClient is the client API for BifExamine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BifExamineClient interface {
	UploadBifKey(ctx context.Context, in *UploadBifKeyRequest, opts ...grpc.CallOption) (*UploadBifKeyResponse, error)
}

type bifExamineClient struct {
	cc grpc.ClientConnInterface
}

func NewBifExamineClient(cc grpc.ClientConnInterface) BifExamineClient {
	return &bifExamineClient{cc}
}

func (c *bifExamineClient) UploadBifKey(ctx context.Context, in *UploadBifKeyRequest, opts ...grpc.CallOption) (*UploadBifKeyResponse, error) {
	out := new(UploadBifKeyResponse)
	err := c.cc.Invoke(ctx, BifExamine_UploadBifKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BifExamineServer is the server API for BifExamine service.
// All implementations must embed UnimplementedBifExamineServer
// for forward compatibility
type BifExamineServer interface {
	UploadBifKey(context.Context, *UploadBifKeyRequest) (*UploadBifKeyResponse, error)
	mustEmbedUnimplementedBifExamineServer()
}

// UnimplementedBifExamineServer must be embedded to have forward compatible implementations.
type UnimplementedBifExamineServer struct {
}

func (UnimplementedBifExamineServer) UploadBifKey(context.Context, *UploadBifKeyRequest) (*UploadBifKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBifKey not implemented")
}
func (UnimplementedBifExamineServer) mustEmbedUnimplementedBifExamineServer() {}

// UnsafeBifExamineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BifExamineServer will
// result in compilation errors.
type UnsafeBifExamineServer interface {
	mustEmbedUnimplementedBifExamineServer()
}

func RegisterBifExamineServer(s grpc.ServiceRegistrar, srv BifExamineServer) {
	s.RegisterService(&BifExamine_ServiceDesc, srv)
}

func _BifExamine_UploadBifKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBifKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BifExamineServer).UploadBifKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BifExamine_UploadBifKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BifExamineServer).UploadBifKey(ctx, req.(*UploadBifKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BifExamine_ServiceDesc is the grpc.ServiceDesc for BifExamine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BifExamine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BifExamine",
	HandlerType: (*BifExamineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadBifKey",
			Handler:    _BifExamine_UploadBifKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/rpc/pb/bif_examine.proto",
}
