// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: pkg/rpc/pb/bif_examine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BifExamine_GetAllProjects_FullMethodName                = "/pb.BifExamine/GetAllProjects"
	BifExamine_GetProjectById_FullMethodName                = "/pb.BifExamine/GetProjectById"
	BifExamine_DeleteProject_FullMethodName                 = "/pb.BifExamine/DeleteProject"
	BifExamine_GetBifsMissingContents_FullMethodName        = "/pb.BifExamine/GetBifsMissingContents"
	BifExamine_GetResourcesMissingBifDetails_FullMethodName = "/pb.BifExamine/GetResourcesMissingBifDetails"
	BifExamine_UploadKey_FullMethodName                     = "/pb.BifExamine/UploadKey"
	BifExamine_UploadBif_FullMethodName                     = "/pb.BifExamine/UploadBif"
	BifExamine_UploadLargeBif_FullMethodName                = "/pb.BifExamine/UploadLargeBif"
	BifExamine_DownloadResource_FullMethodName              = "/pb.BifExamine/DownloadResource"
)

// BifExamineClient is the client API for BifExamine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BifExamineClient interface {
	GetAllProjects(ctx context.Context, in *GetAllProjectsRequest, opts ...grpc.CallOption) (*GetAllProjectsResponse, error)
	GetProjectById(ctx context.Context, in *GetProjectByIdRequest, opts ...grpc.CallOption) (*GetProjectByIdResponse, error)
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error)
	GetBifsMissingContents(ctx context.Context, in *GetBifsMissingContentsRequest, opts ...grpc.CallOption) (*GetBifsMissingContentsResponse, error)
	GetResourcesMissingBifDetails(ctx context.Context, in *GetResourcesMissingBifDetailsRequest, opts ...grpc.CallOption) (*GetResourcesMissingBifDetailsResponse, error)
	UploadKey(ctx context.Context, in *UploadKeyRequest, opts ...grpc.CallOption) (*UploadKeyResponse, error)
	UploadBif(ctx context.Context, in *UploadBifRequest, opts ...grpc.CallOption) (*UploadBifResponse, error)
	UploadLargeBif(ctx context.Context, opts ...grpc.CallOption) (BifExamine_UploadLargeBifClient, error)
	DownloadResource(ctx context.Context, in *DownloadResourceRequest, opts ...grpc.CallOption) (*DownloadResourceResponse, error)
}

type bifExamineClient struct {
	cc grpc.ClientConnInterface
}

func NewBifExamineClient(cc grpc.ClientConnInterface) BifExamineClient {
	return &bifExamineClient{cc}
}

func (c *bifExamineClient) GetAllProjects(ctx context.Context, in *GetAllProjectsRequest, opts ...grpc.CallOption) (*GetAllProjectsResponse, error) {
	out := new(GetAllProjectsResponse)
	err := c.cc.Invoke(ctx, BifExamine_GetAllProjects_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bifExamineClient) GetProjectById(ctx context.Context, in *GetProjectByIdRequest, opts ...grpc.CallOption) (*GetProjectByIdResponse, error) {
	out := new(GetProjectByIdResponse)
	err := c.cc.Invoke(ctx, BifExamine_GetProjectById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bifExamineClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error) {
	out := new(DeleteProjectResponse)
	err := c.cc.Invoke(ctx, BifExamine_DeleteProject_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bifExamineClient) GetBifsMissingContents(ctx context.Context, in *GetBifsMissingContentsRequest, opts ...grpc.CallOption) (*GetBifsMissingContentsResponse, error) {
	out := new(GetBifsMissingContentsResponse)
	err := c.cc.Invoke(ctx, BifExamine_GetBifsMissingContents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bifExamineClient) GetResourcesMissingBifDetails(ctx context.Context, in *GetResourcesMissingBifDetailsRequest, opts ...grpc.CallOption) (*GetResourcesMissingBifDetailsResponse, error) {
	out := new(GetResourcesMissingBifDetailsResponse)
	err := c.cc.Invoke(ctx, BifExamine_GetResourcesMissingBifDetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bifExamineClient) UploadKey(ctx context.Context, in *UploadKeyRequest, opts ...grpc.CallOption) (*UploadKeyResponse, error) {
	out := new(UploadKeyResponse)
	err := c.cc.Invoke(ctx, BifExamine_UploadKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bifExamineClient) UploadBif(ctx context.Context, in *UploadBifRequest, opts ...grpc.CallOption) (*UploadBifResponse, error) {
	out := new(UploadBifResponse)
	err := c.cc.Invoke(ctx, BifExamine_UploadBif_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bifExamineClient) UploadLargeBif(ctx context.Context, opts ...grpc.CallOption) (BifExamine_UploadLargeBifClient, error) {
	stream, err := c.cc.NewStream(ctx, &BifExamine_ServiceDesc.Streams[0], BifExamine_UploadLargeBif_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &bifExamineUploadLargeBifClient{stream}
	return x, nil
}

type BifExamine_UploadLargeBifClient interface {
	Send(*UploadBifRequest) error
	CloseAndRecv() (*UploadBifResponse, error)
	grpc.ClientStream
}

type bifExamineUploadLargeBifClient struct {
	grpc.ClientStream
}

func (x *bifExamineUploadLargeBifClient) Send(m *UploadBifRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bifExamineUploadLargeBifClient) CloseAndRecv() (*UploadBifResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadBifResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bifExamineClient) DownloadResource(ctx context.Context, in *DownloadResourceRequest, opts ...grpc.CallOption) (*DownloadResourceResponse, error) {
	out := new(DownloadResourceResponse)
	err := c.cc.Invoke(ctx, BifExamine_DownloadResource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BifExamineServer is the server API for BifExamine service.
// All implementations must embed UnimplementedBifExamineServer
// for forward compatibility
type BifExamineServer interface {
	GetAllProjects(context.Context, *GetAllProjectsRequest) (*GetAllProjectsResponse, error)
	GetProjectById(context.Context, *GetProjectByIdRequest) (*GetProjectByIdResponse, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error)
	GetBifsMissingContents(context.Context, *GetBifsMissingContentsRequest) (*GetBifsMissingContentsResponse, error)
	GetResourcesMissingBifDetails(context.Context, *GetResourcesMissingBifDetailsRequest) (*GetResourcesMissingBifDetailsResponse, error)
	UploadKey(context.Context, *UploadKeyRequest) (*UploadKeyResponse, error)
	UploadBif(context.Context, *UploadBifRequest) (*UploadBifResponse, error)
	UploadLargeBif(BifExamine_UploadLargeBifServer) error
	DownloadResource(context.Context, *DownloadResourceRequest) (*DownloadResourceResponse, error)
	mustEmbedUnimplementedBifExamineServer()
}

// UnimplementedBifExamineServer must be embedded to have forward compatible implementations.
type UnimplementedBifExamineServer struct {
}

func (UnimplementedBifExamineServer) GetAllProjects(context.Context, *GetAllProjectsRequest) (*GetAllProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllProjects not implemented")
}
func (UnimplementedBifExamineServer) GetProjectById(context.Context, *GetProjectByIdRequest) (*GetProjectByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectById not implemented")
}
func (UnimplementedBifExamineServer) DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedBifExamineServer) GetBifsMissingContents(context.Context, *GetBifsMissingContentsRequest) (*GetBifsMissingContentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBifsMissingContents not implemented")
}
func (UnimplementedBifExamineServer) GetResourcesMissingBifDetails(context.Context, *GetResourcesMissingBifDetailsRequest) (*GetResourcesMissingBifDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourcesMissingBifDetails not implemented")
}
func (UnimplementedBifExamineServer) UploadKey(context.Context, *UploadKeyRequest) (*UploadKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadKey not implemented")
}
func (UnimplementedBifExamineServer) UploadBif(context.Context, *UploadBifRequest) (*UploadBifResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBif not implemented")
}
func (UnimplementedBifExamineServer) UploadLargeBif(BifExamine_UploadLargeBifServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadLargeBif not implemented")
}
func (UnimplementedBifExamineServer) DownloadResource(context.Context, *DownloadResourceRequest) (*DownloadResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadResource not implemented")
}
func (UnimplementedBifExamineServer) mustEmbedUnimplementedBifExamineServer() {}

// UnsafeBifExamineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BifExamineServer will
// result in compilation errors.
type UnsafeBifExamineServer interface {
	mustEmbedUnimplementedBifExamineServer()
}

func RegisterBifExamineServer(s grpc.ServiceRegistrar, srv BifExamineServer) {
	s.RegisterService(&BifExamine_ServiceDesc, srv)
}

func _BifExamine_GetAllProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BifExamineServer).GetAllProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BifExamine_GetAllProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BifExamineServer).GetAllProjects(ctx, req.(*GetAllProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BifExamine_GetProjectById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BifExamineServer).GetProjectById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BifExamine_GetProjectById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BifExamineServer).GetProjectById(ctx, req.(*GetProjectByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BifExamine_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BifExamineServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BifExamine_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BifExamineServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BifExamine_GetBifsMissingContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBifsMissingContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BifExamineServer).GetBifsMissingContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BifExamine_GetBifsMissingContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BifExamineServer).GetBifsMissingContents(ctx, req.(*GetBifsMissingContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BifExamine_GetResourcesMissingBifDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourcesMissingBifDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BifExamineServer).GetResourcesMissingBifDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BifExamine_GetResourcesMissingBifDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BifExamineServer).GetResourcesMissingBifDetails(ctx, req.(*GetResourcesMissingBifDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BifExamine_UploadKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BifExamineServer).UploadKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BifExamine_UploadKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BifExamineServer).UploadKey(ctx, req.(*UploadKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BifExamine_UploadBif_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBifRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BifExamineServer).UploadBif(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BifExamine_UploadBif_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BifExamineServer).UploadBif(ctx, req.(*UploadBifRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BifExamine_UploadLargeBif_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BifExamineServer).UploadLargeBif(&bifExamineUploadLargeBifServer{stream})
}

type BifExamine_UploadLargeBifServer interface {
	SendAndClose(*UploadBifResponse) error
	Recv() (*UploadBifRequest, error)
	grpc.ServerStream
}

type bifExamineUploadLargeBifServer struct {
	grpc.ServerStream
}

func (x *bifExamineUploadLargeBifServer) SendAndClose(m *UploadBifResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bifExamineUploadLargeBifServer) Recv() (*UploadBifRequest, error) {
	m := new(UploadBifRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BifExamine_DownloadResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BifExamineServer).DownloadResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BifExamine_DownloadResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BifExamineServer).DownloadResource(ctx, req.(*DownloadResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BifExamine_ServiceDesc is the grpc.ServiceDesc for BifExamine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BifExamine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BifExamine",
	HandlerType: (*BifExamineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllProjects",
			Handler:    _BifExamine_GetAllProjects_Handler,
		},
		{
			MethodName: "GetProjectById",
			Handler:    _BifExamine_GetProjectById_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _BifExamine_DeleteProject_Handler,
		},
		{
			MethodName: "GetBifsMissingContents",
			Handler:    _BifExamine_GetBifsMissingContents_Handler,
		},
		{
			MethodName: "GetResourcesMissingBifDetails",
			Handler:    _BifExamine_GetResourcesMissingBifDetails_Handler,
		},
		{
			MethodName: "UploadKey",
			Handler:    _BifExamine_UploadKey_Handler,
		},
		{
			MethodName: "UploadBif",
			Handler:    _BifExamine_UploadBif_Handler,
		},
		{
			MethodName: "DownloadResource",
			Handler:    _BifExamine_DownloadResource_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadLargeBif",
			Handler:       _BifExamine_UploadLargeBif_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/rpc/pb/bif_examine.proto",
}
