version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 6a6009de9ad94e098b327db02706b3bc
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    logging:
      driver: none
    ports:
      - 8080:8080

  minio:
    image: bitnami/minio:latest
    environment:
      MINIO_ROOT_USER:     d91c17035d5e4354b83308c307c2d161
      MINIO_ROOT_PASSWORD: a34b63ea9a95441eb02d7e26676624db
      # Create an access key by logging into minio at localhost:9001 with the above credentials
    volumes:
      - ./minio:/data
    ports:
      - 9000:9000
      - 9001:9001
